services:
    geth:
        image: "ethereum/client-go:${GETH_TAG}"
        volumes:
            - "${EXECUTION_DATA}:/root/.ethereum"
            - ./jwtsecret.txt:/jwtsecret:ro
        ports:
            - "${EXECUTION_P2P_PORT}:${EXECUTION_P2P_PORT}/tcp"
            - "${EXECUTION_P2P_PORT}:${EXECUTION_P2P_PORT}/udp"
        command: >-
            --${NETWORK}
            --port ${EXECUTION_P2P_PORT}
            --maxpeers ${GETH_PEERS}
            --http --http.addr "0.0.0.0" --http.vhosts=* --http.api "eth,net"
            --authrpc.addr "0.0.0.0" --authrpc.vhosts=* --authrpc.jwtsecret /jwtsecret
            --ipcdisable
        restart: always
        stop_grace_period: 3m
    lighthouse:
        image: sigp/lighthouse:${LIGHTHOUSE_TAG}
        volumes:
            - "${CONSENSUS_DATA}:/root/.lighthouse"
            - ./jwtsecret.txt:/jwtsecret:ro
        ports:
            - "${CONSENSUS_P2P_PORT}:${CONSENSUS_P2P_PORT}/tcp"
            - "${CONSENSUS_P2P_PORT}:${CONSENSUS_P2P_PORT}/udp"
        entrypoint: /usr/local/bin/lighthouse
        command: >-
            --network ${NETWORK}
            beacon_node
            --port ${CONSENSUS_P2P_PORT}
            --discovery-port ${CONSENSUS_P2P_PORT}
            --disable-upnp
            --subscribe-all-subnets
            --import-all-attestations
            --target-peers ${LIGHTHOUSE_PEERS}
            ${LIGHTHOUSE_BN_MEVBOOST_FLAGS}
            --http --http-address 0.0.0.0
            --private
            --execution-endpoint http://geth:8551 --execution-jwt /jwtsecret
            --suggested-fee-recipient ${DEFAULT_FEE_RECIPIENT}
        restart: always
        stop_grace_period: 3m
    lighthouse_validator:
        image: sigp/lighthouse:${LIGHTHOUSE_TAG}
        volumes:
            - "${VALIDATOR_DATA}:/root/.lighthouse"
        ports:
            # Expose keymanager API to the host machine.
            - "127.0.0.1:${KEYMANAGER_PORT}:${KEYMANAGER_PORT}/tcp"
        depends_on:
            - lighthouse
        entrypoint: /usr/local/bin/lighthouse
        command: >-
            --network ${NETWORK}
            validator
            --enable-doppelganger-protection
            --suggested-fee-recipient ${DEFAULT_FEE_RECIPIENT}
            --beacon-nodes http://lighthouse:5052
            ${LIGHTHOUSE_VC_MEVBOOST_FLAGS}
            --http --http-address=0.0.0.0 --http-port=${KEYMANAGER_PORT} --unencrypted-http-transport
        restart: always
        stop_grace_period: 3m
    mevboost:
        image: flashbots/mev-boost:${MEVBOOST_TAG}
        restart: always
        profiles:
          - mevboost
        command: >-
          -addr 0.0.0.0:18550
          -${NETWORK}
          -relay-check
          -relays ${MEVBOOST_RELAYS}
