version: "3.0"

services:
    geth:
        image: "ethereum/client-go:${GETH_TAG}"
        volumes:
            - "${EXECUTION_DATA}:/root/.ethereum"
        ports:
            - "${EXECUTION_P2P_PORT}:${EXECUTION_P2P_PORT}/tcp"
            - "${EXECUTION_P2P_PORT}:${EXECUTION_P2P_PORT}/udp"
        command: >-
            --${NETWORK}
            --port ${EXECUTION_P2P_PORT}
            --http --http.addr "0.0.0.0" --http.vhosts=* --http.api "eth,net"
            --ipcdisable
        restart: always
        stop_grace_period: 3m
    lighthouse:
        image: sigp/lighthouse:${LIGHTHOUSE_TAG}
        volumes:
            - "${CONSENSUS_DATA}:/root/.lighthouse"
        ports:
            - "${CONSENSUS_P2P_PORT}:${CONSENSUS_P2P_PORT}/tcp"
            - "${CONSENSUS_P2P_PORT}:${CONSENSUS_P2P_PORT}/udp"
        entrypoint: /usr/local/bin/lighthouse
        command: >-
            --network ${NETWORK}
	        beacon_node
	        --eth1-endpoints http://geth:8545
	        --http
	        --http-address 0.0.0.0
            --private
            --eth1
        restart: always
        stop_grace_period: 3m
    lighthouse_validator:
        image: sigp/lighthouse:${LIGHTHOUSE_TAG}
        volumes:
            - "${CONSENSUS_DATA}:/root/.lighthouse"
            - ./scripts:/root/scripts:ro
            - ./validator_keys:/root/validator_keys:ro
        depends_on:
            - lighthouse
        environment:
            - KEYSTORE_PASSWD
            - NETWORK
        entrypoint: /bin/sh
        command: /root/scripts/start-validator-client.sh
        restart: always
        stop_grace_period: 3m
